#!/usr/bin/env python3
"""Consolidate AB prompt results into a summary file.

Scans audit_results for prompt_ab_*.json results and writes a consolidated summary
to audit_results/prompt_ab_consolidated_summary.json.
"""

from __future__ import annotations

import glob
import json
from pathlib import Path

OUTPUT = Path("audit_results/prompt_ab_consolidated_summary.json")


def main():
    records = []
    for path in sorted(glob.glob("audit_results/prompt_ab_*.json")):
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            model = data.get("model", Path(path).stem)
            # Try to grab variant A/B results if present
            records.append({"model": model, "data": data})
        except Exception:
            continue
    consolidated = {
        "consolidated": records,
        "note": "Auto-generated by ab_consolidator.py",
    }
    OUTPUT.write_text(json.dumps(consolidated, indent=2), encoding="utf-8")
    print(f"Wrote consolidated summary to {OUTPUT}")


if __name__ == "__main__":
    main()
